name: 'build-trojanx-rpm-action'
description: 'Build TrojanX rpm package.'
author: 'M1Screw'
inputs:
  bin:
    description: 'binary file path'
    required: true
  spec:
    description: 'spec file path'
    required: true
  config:
    description: 'config file path'
    required: true
  service:
    description: 'service file path'
    required: true

# Ref: https://haya14busa.github.io/github-action-brandings/
# TODO: update branding if you want.
branding:
  icon: 'check'
  color: 'blue'
